CREATE TABLE alunos(
id INTEGER,
nome TEXT,
cgu NUMERIC NOT NULL,
PRIMARY KEY(id AUTOINCREMENT)
);
CREATE TABLE contato(
id INTEGER,
id_aluno NUMERIC,
fone TEXT,
email TEXT,
cgu NUMERIC NOT NULL,
PRIMARY KEY(id AUTOINCREMENT),
FOREIGN KEY (id_aluno) REFERENCES alunos(id)
);